=== Aptima/DDD/VisualScenarioGenerator/VSG/Models/vsg/xsd/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by Danny Lecours (Aptima, Inc.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Constraint">
		<xs:complexType>
			<xs:attribute name="constraintName" type="xs:string" use="required"/>
			<xs:attribute name="constraintValue" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Value"/>
	<xs:element name="Enum">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Value" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="enumName" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Enums">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Enum" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Constraints">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Constraint" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="firstCapital">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z].*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Parameter">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="Constraints" minOccurs="0"/>
				<xs:element name="Parameters" minOccurs="0">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="Parameter">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Constraints" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="type" type="xs:string" use="required"/>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="value" type="xs:string" use="optional"/>
									<xs:attribute name="description" type="xs:string" use="optional"/>
									<xs:attribute name="editor" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="displayedName" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="optional"/>
			<xs:attribute name="category" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
			<xs:attribute name="readOnly" type="xs:boolean" use="optional"/>
			<xs:attribute name="browsable" type="xs:boolean" use="optional"/>
			<xs:attribute name="classOnly" type="xs:boolean" use="optional"/>
			<xs:attribute name="editor" type="xs:string" use="optional"/>
			<xs:attribute name="propertyName" type="xs:string" use="optional"/>
			<xs:attribute name="isOutput" type="xs:boolean" use="optional"/>
			<xs:attribute name="typeconverter" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ComplexParameters">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Parameters"/>
				<xs:element ref="Enums" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="defaultParameter" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="GME">
		<xs:annotation>
			<xs:documentation>Configuration file</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Configurations">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Configuration" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Components" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element ref="Component" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
											<xs:unique name="unique_component_name">
												<xs:selector xpath="Component"/>
												<xs:field xpath="@name"/>
											</xs:unique>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="root" type="xs:string" use="optional"/>
									<xs:attribute name="controller" type="xs:string" use="required"/>
									<xs:attribute name="linkType" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="unique_configuration_name">
						<xs:selector xpath="Configuration"/>
						<xs:field xpath="@name"/>
					</xs:unique>
				</xs:element>
				<xs:element name="Global">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="4">
							<xs:element name="Components" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Component" maxOccurs="unbounded">
											<xs:complexType>
												<xs:all>
													<xs:element ref="CreateComponents" minOccurs="0"/>
													<xs:element ref="CreateLinks" minOccurs="0"/>
													<xs:element ref="ComplexParameters" minOccurs="0"/>
													<xs:element name="EngineModel" minOccurs="0">
														<xs:complexType>
															<xs:complexContent>
																<xs:extension base="EngineModelType">
																	<xs:attribute name="link" type="xs:string" use="required"/>
																</xs:extension>
															</xs:complexContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="Inputs" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Input" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="Links" minOccurs="0">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="Link" minOccurs="0" maxOccurs="unbounded">
																							<xs:complexType>
																								<xs:attribute name="type" type="xs:string" use="required"/>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																		<xs:attribute name="name" type="xs:string" use="required"/>
																		<xs:attribute name="link" type="xs:string" use="required"/>
																		<xs:attribute name="selectable" type="xs:boolean" use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:all>
												<xs:attribute name="type" type="xs:string" use="optional"/>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="base" type="xs:string" use="optional"/>
												<xs:attribute name="bitmap" type="xs:string" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
								<xs:unique name="ComponentNameKey">
									<xs:selector xpath="Component"/>
									<xs:field xpath="@name"/>
								</xs:unique>
							</xs:element>
							<xs:element ref="Links" minOccurs="0"/>
							<xs:element ref="Enums" minOccurs="0"/>
							<xs:element ref="Adapters" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Component">
		<xs:complexType>
			<xs:all>
				<xs:element name="SubComponents" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Component" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
			<xs:attribute name="type" type="xs:string" use="optional"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="bitmap" type="xs:string" use="optional"/>
			<xs:attribute name="displayName" type="xs:string" use="optional"/>
			<xs:attribute name="graphType" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Link">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Connect" maxOccurs="unbounded"/>
				<xs:element name="Dynamic" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="component" type="xs:string" use="optional"/>
						<xs:attribute name="refLinkType" type="xs:string" use="optional"/>
						<xs:attribute name="refLinkTypeDynamic" type="xs:boolean" use="optional" default="true"/>
						<xs:attribute name="isRoot" type="xs:string" use="required"/>
						<xs:attribute name="appCode" type="xs:string" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="BridgeDynamic" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="component" type="xs:string" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="dynamicType" type="xs:string" use="optional"/>
			<xs:attribute name="deepCopy" type="xs:boolean" use="optional"/>
			<xs:attribute name="schemaFilename" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Connect">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ComplexParameters" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="from" type="xs:string" use="required"/>
			<xs:attribute name="to" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CreateComponents">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CreateComponent" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CreateLinks">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CreateLink" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CreateParameter" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="value" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="configuration" type="xs:string" use="required"/>
						<xs:attribute name="schemaRoot" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Root"/>
									<xs:enumeration value="Parent"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="from" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Root"/>
									<xs:enumeration value="Parent"/>
									<xs:enumeration value="Self"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="to" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Parent"/>
									<xs:enumeration value="Self"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Links">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Link" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="UniqueTypes">
			<xs:selector xpath="Link"/>
			<xs:field xpath="@type"/>
		</xs:unique>
	</xs:element>
	<xs:element name="CreateComponent">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CreateLinks" minOccurs="0"/>
				<xs:element name="CreateParameters" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CreateParameter" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="value" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="CreateComponent" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="component" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="configuration" type="xs:string" use="required"/>
			<xs:attribute name="eType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Component"/>
						<xs:enumeration value="Class"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="uid" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="EngineModelType">
		<xs:sequence>
			<xs:element name="Adapters" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Adapter" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="type" type="xs:string" use="required"/>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="fullname" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Inputs" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Input" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Links" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Link" minOccurs="0" maxOccurs="unbounded">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="Include" minOccurs="0" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:attribute name="componentType" type="xs:string" use="required"/>
																	<xs:attribute name="isDynamic" type="xs:boolean" use="required"/>
																	<xs:attribute name="linkType" type="xs:string" use="required"/>
																	<xs:attribute name="level" type="xs:int" use="optional"/>
																	<xs:attribute name="includeParameters" type="xs:boolean" use="optional"/>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
														<xs:attribute name="type" type="xs:string" use="required"/>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="link" type="xs:string" use="required"/>
								<xs:attribute name="selectable" type="xs:boolean" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
				<xs:unique name="InputNameKey">
					<xs:selector xpath="Input"/>
					<xs:field xpath="@name"/>
				</xs:unique>
			</xs:element>
			<xs:element name="Outputs" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Output" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="type" type="xs:string" use="required"/>
								<xs:attribute name="name" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="assembly" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Adapters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Adapter" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="display" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string"/>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="Type">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Assembly" type="xs:string"/>
										<xs:element name="Namespace" type="xs:string"/>
										<xs:element name="Name" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="kind" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Import"/>
									<xs:enumeration value="Export"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Aptima/DDD/VisualScenarioGenerator/VSG/Models/vsg/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<GME xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/configuration.xsd">
	<Configurations>
		<Configuration name="Project" root="Scenario" controller="RootController" linkType="Scenario"/>
		<Configuration name="VSG" root="Scenario" controller="VSG.Controllers.VSGController" linkType="Scenario"/>
	</Configurations>
	<Global>
		<Components>
			<Component name="Scenario" bitmap="Folder.ico">
				<CreateComponents>
					<CreateComponent component="Playfield" name="Playfield" configuration="VSG" eType="Component">
						<CreateLinks>
							<CreateLink name="Scenario" configuration="VSG" schemaRoot="Root" from="Parent" to="Self"/>
						</CreateLinks>
					</CreateComponent>
				</CreateComponents>
				<ComplexParameters>
					<Parameters>
						<Parameter propertyName="ScenarioName" type="System.String" displayedName="Scenario Name" value="" category="Scenario" description="Name of Scenario"/>
						<Parameter propertyName="Description" type="System.String" displayedName="Description" value="" category="Scenario" description="Description of scenario"/>
						<Parameter propertyName="TimeToAttack" type="System.Int32" displayedName="Time To Attack" value="10" category="Scenario" description="Time To Attack"/>
						<Parameter propertyName="AssetTransfer" type="System.Boolean" displayedName="Allow Asset Transfers" value="false" category="Scenario" description="Enables or disables the ability for Decision Makers to be able to transfer assets between each other."/>
						<Parameter propertyName="RangeRingDisplayType" type="RangeRingDisplayEnum" displayedName="Range Ring Display Type" value="Full" category="Scenario" description="Range Ring Client Display Value" />
					</Parameters>
					<Enums>
					<Enum enumName="RangeRingDisplayEnum">
						<Value>Full</Value>
						<Value>Shared Sensor Network</Value>
						<Value>Personal</Value>
						<Value>Disabled</Value>
						</Enum>
					</Enums>
				</ComplexParameters>
			</Component>
			<Component name="Playfield">
				<ComplexParameters>
					<Parameters>
						<Parameter propertyName="MapFileName" type="System.String" displayedName="Map Filename" value="" category="Playfield" description="Map Filename"/>
						<Parameter propertyName="IconLibrary" type="System.String" displayedName="Icon Library" value="" category="Playfield" description="Icon Library"/>
						<Parameter propertyName="UtmZone" type="System.String" displayedName="UTM Zone" value="None" category="Playfield" description="UTM Zone"/>
						<Parameter propertyName="VerticalScale" type="System.Decimal" displayedName="Vertical Scale" value="1.0" category="Playfield" description="Vertical Scale">
							<Constraints>
								<Constraint constraintName="min" constraintValue="0.001"/>
								<Constraint constraintName="max" constraintValue="5000"/>
							</Constraints>
						</Parameter>
						<Parameter propertyName="HorizontalScale" type="System.Decimal" displayedName="Horizontal Scale" value="1.0" category="Playfield" description="Horizontal Scale">
							<Constraints>
								<Constraint constraintName="min" constraintValue="0.001"/>
								<Constraint constraintName="max" constraintValue="5000"/>
							</Constraints>
						</Parameter>
						<Parameter propertyName="Northing" type="System.Decimal" displayedName="Northing" value="0.0" category="Playfield" description="Northing"/>
						<Parameter propertyName="Easting" type="System.Decimal" displayedName="Easting" value="0.0" category="Playfield" description="Easting"/>
						<Parameter propertyName="DefaultDisplayLabels" type="System.String" displayedName="Display Labels" value="" category="Playfield" description="If labels are displayed by default, or disabled"/>
						<Parameter propertyName="DefaultDisplayTags" type="System.String" displayedName="Display Tags" value="" category="Playfield" description="If tags are displayed by default, or disabled."/>
					</Parameters>
				</ComplexParameters>
			</Component>
			<Component name="LandRegion">
				<ComplexParameters>
					<Parameters>
						<Parameter propertyName="PolygonPoints" type="System.String" displayedName="Polygon Points" value="" category="Location" description="Location of the Land Region"/>
						<Parameter propertyName="Color" type="System.Drawing.Color, System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" displayedName="Color" value="Brown" category="Color" description="Color"/>
						<Parameter propertyName="Alpha" type="System.String" displayedName="Alpha" value="" category="Color" description="Alpha"/>
					</Parameters>
					<Enums>
						<Enum enumName="Colors">
							<Value>AliceBlue</Value>
							<Value>Aqua</Value>
							<Value>Blue</Value>
							<Value>BlueViolet</Value>
							<Value>Brown</Value>
							<Value>CornflowerBlue</Value>
							<Value>Crimson</Value>
							<Value>Cyan</Value>
							<Value>DarkBlue</Value>
							<Value>DarkGray</Value>
							<Value>DarkGreen</Value>
							<Value>DarkKhaki</Value>
							<Value>DarkOliveGreen</Value>
							<Value>DarkRed</Value>
							<Value>DarkSlateGray</Value>
							<Value>DodgerBlue</Value>
							<Value>Fuchsia</Value>
							<Value>Gray</Value>
							<Value>Green</Value>
							<Value>GreenYellow</Value>
							<Value>HotPink</Value>
							<Value>Khaki</Value>
							<Value>Lavender</Value>
							<Value>LimeGreen</Value>
							<Value>Magenta</Value>
							<Value>Maroon</Value>
							<Value>Navy</Value>
							<Value>Olive</Value>
							<Value>OliveDrab</Value>
							<Value>Orange</Value>
							<Value>OrangeRed</Value>
							<Value>Plum</Value>
							<Value>PowderBlue</Value>
							<Value>Purple</Value>
							<Value>Red</Value>
							<Value>RosyBrown</Value>
							<Value>RoyalBlue</Value>
							<Value>SandyBrown</Value>
							<Value>SeaGreen</Value>
							<Value>Silver</Value>
							<Value>SkyBlue</Value>
							<Value>SlateBlue</Value>
							<Value>SlateGray</Value>
							<Value>Tan</Value>
							<Value>Teal</Value>
							<Value>Transparent</Value>
							<Value>Turquoise</Value>
							<Value>Violet</Value>
							<Value>Yellow</Value>
							<Value>YellowGreen</Value>
						</Enum>
					</Enums>
				</ComplexParameters>
			</Component>
			<Component name="ActiveRegion">
				<ComplexParameters>
					<Parameters>
						<Parameter propertyName="PolygonPoints" type="System.String" displayedName="Polygon Points" value="" category="Location" description="Location of the Land Region"/>
						<Parameter propertyName="Color" type="System.Drawing.Color, System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" displayedName="Color" value="DarkGreen" category="Color" description="Color"/>
						<Parameter propertyName="Alpha" type="System.String" displayedName="Alpha" value="" category="Color" description="Alpha"/>
						<Parameter propertyName="Start" type="System.Decimal" displayedName="Start" value="0.0" category="Active Region" description="Start"/>
						<Parameter propertyName="End" type="System.Decimal" displayedName="End" value="0.0" category="Active Region" description="End"/>
						<Parameter propertyName="SpeedMultiplier" type="System.Decimal" displayedName="Speed Multiplier" value="1.0" category="Active Region" description="Speed Multiplier"/>
						<Parameter propertyName="BlocksMovement" type="System.Boolean" displayedName="Blocks Movement" value="false" category="Active Region" description="Blocks Movement"/>
						<Parameter propertyName="SensorsBlocked" type="System.String" displayedName="Sensors Blocked" value="" category="Active Region" description="Sensors Blocked"/>
						<Parameter propertyName="IsVisible" type="System.Boolean" displayedName="Is Visible" value="true" category="Active Region" description="Is Visible"/>
						<Parameter propertyName="ReferencePoint" type="System.String" displayedName="ReferencePoint" value="" category="Location" description="Reference point of the Active Region"/>
						
						<Parameter propertyName="IsDynamicRegion" type="System.Boolean" displayedName="Is this a Dynamic Region" value="false" category="Active Region" description="Is this object a dynamic region, tied to an instantiation of an object"/>
						<Parameter propertyName="RelativePolygonPoints" type="System.String" displayedName="Relative Polygon Points" value="" category="Location" description="Relative Location of the Active Region"/>
						
					</Parameters>
					<Enums>
						<Enum enumName="Colors">
							<Value>AliceBlue</Value>
							<Value>Aqua</Value>
							<Value>Blue</Value>
							<Value>BlueViolet</Value>
							<Value>Brown</Value>
							<Value>CornflowerBlue</Value>
							<Value>Crimson</Value>
							<Value>Cyan</Value>
							<Value>DarkBlue</Value>
							<Value>DarkGray</Value>
							<Value>DarkGreen</Value>
							<Value>DarkKhaki</Value>
							<Value>DarkOliveGreen</Value>
							<Value>DarkRed</Value>
							<Value>DarkSlateGray</Value>
							<Value>DodgerBlue</Value>
							<Value>Fuchsia</Value>
							<Value>Gray</Value>
							<Value>Green</Value>
							<Value>GreenYellow</Value>
							<Value>HotPink</Value>
							<Value>Khaki</Value>
							<Value>Lavender</Value>
							<Value>LimeGreen</Value>
							<Value>Magenta</Value>
							<Value>Maroon</Value>
							<Value>Navy</Value>
							<Value>Olive</Value>
							<Value>OliveDrab</Value>
							<Value>Orange</Value>
							<Value>OrangeRed</Value>
							<Value>Plum</Value>
							<Value>PowderBlue</Value>
							<Value>Purple</Value>
							<Value>Red</Value>
							<Value>RosyBrown</Value>
							<Value>RoyalBlue</Value>
							<Value>SandyBrown</Value>
							<Value>SeaGreen</Value>
							<Value>Silver</Value>
							<Value>SkyBlue</Value>
							<Value>SlateBlue</Value>
							<Value>SlateGray</Value>
							<Value>Tan</Value>
							<Value>Teal</Value>
							<Value>Transparent</Value>
							<Value>Turquoise</Value>
							<Value>Violet</Value>
