=== Aptima/DDD/BatchRunner/BatchRunner.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by Danny Lecours (Aptima) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="BatchRunner">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="RunInfo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="RunName" type="xs:string"/>
							<xs:element name="RunScenarioPath" type="xs:string"/>
							<xs:element name="RunLogDirectoryPath" type="xs:string"/>
							<xs:element name="RunDataTag" type="xs:string"/>
							<xs:element name="RunDuration" type="xs:int"/>
							<xs:element name="ExternalSetupCommand" type="xs:string"/>
							<xs:element name="ExternalSetupArguments"/>
							<xs:element name="ExternalSetupWorkingDirectory"/>
							<xs:element name="ExternalSetupDelay" type="xs:int"/>
							<xs:element name="ExternalTeardownCommand" type="xs:string"/>
							<xs:element name="ExternalTeardownArguments"/>
							<xs:element name="ExternalTeardownWorkingDirectory"/>
							<xs:element name="ExternalTeardownDelay" type="xs:int"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Aptima/DDD/BatchRunner/testBatch.xml
<?xml version="1.0" encoding="UTF-8"?>
<BatchRunner xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\dev\svnroot\phoenix\src\BatchRunner\BatchRunner.xsd">
<RunInfo>
	<RunName>run1</RunName>
	<RunScenarioPath>C:\Users\ganberg\dev\svnroot\AFAR\AFAR1_A.xml</RunScenarioPath>
	<RunLogDirectoryPath>.</RunLogDirectoryPath>
	<RunDataTag>1</RunDataTag>
	<RunDuration>15</RunDuration>
	<ExternalSetupCommand>AFAR Airport View.exe</ExternalSetupCommand>
	<ExternalSetupArguments>localhost 9999 Test_A.xml</ExternalSetupArguments>
	<ExternalSetupWorkingDirectory>C:\Users\ganberg\dev\svnroot\AFAR\src\AFAR Airport View\bin\x64\Debug</ExternalSetupWorkingDirectory>
	<ExternalSetupDelay>10</ExternalSetupDelay>
	<ExternalTeardownCommand></ExternalTeardownCommand>
	<ExternalTeardownArguments></ExternalTeardownArguments>
	<ExternalTeardownWorkingDirectory></ExternalTeardownWorkingDirectory>
	<ExternalTeardownDelay>1</ExternalTeardownDelay>
</RunInfo>
<RunInfo>
	<RunName>run2</RunName>
	<RunScenarioPath>C:\Users\ganberg\dev\svnroot\AFAR\AFAR1_A.xml</RunScenarioPath>
	<RunLogDirectoryPath>.</RunLogDirectoryPath>
	<RunDataTag>2</RunDataTag>
	<RunDuration>15</RunDuration>
	<ExternalSetupCommand>C:\Users\ganberg\dev\svnroot\AFAR\src\AFAR Airport View\bin\x64\Debug\AFAR Airport View.exe</ExternalSetupCommand>
	<ExternalSetupArguments>localhost 9999 Test_A.xml</ExternalSetupArguments>
	<ExternalSetupWorkingDirectory>C:\Users\ganberg\dev\svnroot\AFAR\src\AFAR Airport View\bin\x64\Debug\</ExternalSetupWorkingDirectory>
	<ExternalSetupDelay>10</ExternalSetupDelay>
	<ExternalTeardownCommand></ExternalTeardownCommand>
	<ExternalTeardownArguments></ExternalTeardownArguments>
	<ExternalTeardownWorkingDirectory></ExternalTeardownWorkingDirectory>
	<ExternalTeardownDelay>1</ExternalTeardownDelay>
</RunInfo>
</BatchRunner>
