=== Aptima/DDD/Agents/SEAMATE Item Generator/tags/dec2011tag/SeamateRuntimeEngine/xsd/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by Adam Dziki (Aptima) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="T_TODO"/>
	<xs:complexType name="T_StartupParameters">
		<xs:sequence maxOccurs="unbounded">
			<xs:element ref="Parameter"/>
			<xs:element ref="Setting"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_Reveal">
		<xs:sequence>
			<xs:element ref="ID"/>
			<xs:element ref="Type" minOccurs="0"/>
			<xs:element ref="Owner" minOccurs="0"/>
			<xs:element ref="Location"/>
			<xs:element ref="State"/>
			<xs:element ref="StartupParameters" minOccurs="0"/>
			<xs:element ref="TimeAfter"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_RelativePosition">
		<xs:sequence>
			<xs:element ref="DistanceConstraint"/>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="PosID"/>
					<xs:element ref="Type"/>
				</xs:sequence>
				<xs:element ref="AbsolutePosition"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_Prerequisite">
		<xs:sequence>
			<xs:element ref="TODO"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_Move">
		<xs:sequence>
			<xs:element ref="ID"/>
			<xs:element ref="Location"/>
			<xs:element ref="TimeAfter"/>
			<xs:element name="Throttle" type="xs:double"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_Location">
		<xs:choice>
			<xs:element ref="AbsolutePosition"/>
			<xs:element ref="RelativePosition"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="T_Items">
		<xs:sequence>
			<xs:element ref="Item" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_SeamateItems">
		<xs:sequence>
			<xs:element ref="Timeline"/>
			<xs:element ref="Items"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_Item">
		<xs:sequence>
			<xs:element ref="ID"/>
			<xs:element ref="Parameters"/>
			<xs:element ref="Prerequisite" minOccurs="0"/>
			<xs:element ref="Action"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_Interaction">
		<xs:sequence>
			<xs:element ref="Instigator"/>
			<xs:element ref="Target"/>
			<xs:element ref="Capability"/>
			<xs:element ref="TimeAfter"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_ChangeState">
		<xs:sequence>
			<xs:element ref="ID"/>
			<xs:element ref="State"/>
			<xs:element ref="TimeAfter"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_ScriptedItem">
		<xs:sequence>
			<xs:element ref="ID"/>
			<xs:element ref="ActionType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_Action">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="Move"/>
			<xs:element ref="Reveal"/>
			<xs:element ref="Interaction"/>
			<xs:element ref="ChangeState"/>
			<xs:element ref="ScriptedItem"/>
		</xs:choice>
	</xs:complexType>
	<xs:simpleType name="T_Groupings">
		<xs:restriction base="xs:string">
			<xs:enumeration value="One"/>
			<xs:enumeration value="Two"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="T_AbsolutePosition">
		<xs:sequence>
			<xs:element ref="X"/>
			<xs:element ref="Y"/>
			<xs:element ref="Z"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Z" type="xs:decimal"/>
	<xs:element name="Y" type="xs:decimal"/>
	<xs:element name="X" type="xs:decimal"/>
	<xs:element name="Time" type="xs:int"/>
	<xs:element name="Target" type="xs:string"/>
	<xs:element name="TODO" type="T_TODO"/>
	<xs:element name="State" type="xs:string"/>
	<xs:element name="StartupParameters" type="T_StartupParameters"/>
	<xs:element name="Setting" type="xs:string"/>
	<xs:element name="Reveal" type="T_Reveal"/>
	<xs:element name="RelativePosition" type="T_RelativePosition"/>
	<xs:element name="Prerequisite" type="T_Prerequisite"/>
	<xs:element name="Parameter" type="xs:string"/>
	<xs:element name="Owner" type="xs:string"/>
	<xs:element name="Type" type="xs:string"/>
	<xs:element name="Move" type="T_Move"/>
	<xs:element name="Location" type="T_Location"/>
	<xs:element name="Items" type="T_Items"/>
	<xs:element name="SeamateItems" type="T_SeamateItems"/>
	<xs:element name="Item" type="T_Item"/>
	<xs:element name="Interaction" type="T_Interaction"/>
	<xs:element name="Instigator" type="xs:string"/>
	<xs:element name="ID" type="xs:string"/>
	<xs:element name="DistanceConstraint" type="xs:decimal"/>
	<xs:element name="ChangeState" type="T_ChangeState"/>
	<xs:element name="ScriptedItem" type="T_ScriptedItem"/>
	<xs:element name="Capability" type="xs:string"/>
	<xs:element name="PosID" type="xs:string"/>
	<xs:element name="Action" type="T_Action"/>
	<xs:element name="AbsolutePosition" type="T_AbsolutePosition"/>
	<xs:element name="Timeline">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ScheduledItem" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ScheduledItem">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Time"/>
				<xs:element ref="ID"/>
				<xs:element ref="DM_ID"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="T_ThreatType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Imminent"/>
			<xs:enumeration value="Non-imminent"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="T_Threat">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Ambiguous"/>
			<xs:enumeration value="Unambiguous"/>
			<xs:enumeration value="None"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="T_ResourceAvailability">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Available"/>
			<xs:enumeration value="Unavailable"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Crossing" type="xs:boolean"/>
				<xs:element name="Groupings" type="T_Groupings"/>
				<xs:element name="Threat" type="T_Threat"/>
				<xs:element name="ThreatType" type="T_ThreatType" minOccurs="0"/>
				<xs:element name="PlayerResources" type="T_ResourceAvailability"/>
				<xs:element name="TeammateResources" type="T_ResourceAvailability"/>
				<xs:element name="Difficulty" type="xs:double"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DM_ID" type="xs:string"/>
	<xs:element name="TimeAfter" type="xs:int"/>
	<xs:element name="ActionType" type="xs:string"/>
</xs:schema>

=== Aptima/DDD/Agents/SEAMATE Item Generator/tags/dec2011tag/SeamateRuntimeEngine/xsd/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<SeamateItems xsi:noNamespaceSchemaLocation="items.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Timeline>
		<ScheduledItem>
			<Time>10</Time>
			<ID>4</ID>
			<DM_ID>BAMS DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>70</Time>
			<ID>2</ID>
			<DM_ID>BAMS DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>130</Time>
			<ID>15</ID>
			<DM_ID>BAMS DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>190</Time>
			<ID>60</ID>
			<DM_ID>BAMS DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>250</Time>
			<ID>1</ID>
			<DM_ID>BAMS DM</DM_ID>
		</ScheduledItem>
		
	</Timeline>
	<Items>
		<Item>
			<ID>1</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>One</Groupings>
				<Threat>Unambiguous</Threat>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
		<Item>
			<ID>2</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>One</Groupings>
				<Threat>Ambiguous</Threat>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				<Reveal>
					<ID>5069</ID>
					<Location>
						<AbsolutePosition>
							<X>125300</X>
							<Y>16600</Y>
							<Z>0</Z>
						</AbsolutePosition>
					</Location>
					<State>FullyFunctional</State>
					<TimeAfter>7</TimeAfter>
				</Reveal>
				<Reveal>
					<ID>9809</ID>
					<Location>
						<AbsolutePosition>
							<X>125400</X>
							<Y>27200</Y>
							<Z>0</Z>
						</AbsolutePosition>
					</Location>
					<State>FullyFunctional</State>
					<TimeAfter>2</TimeAfter>
				</Reveal>
				<Move>
					<ID>5069</ID>
					<Location>
						<AbsolutePosition>
							<X>86600</X>
							<Y>59200</Y>
							<Z>0</Z>
						</AbsolutePosition>
					</Location>
					<TimeAfter>8</TimeAfter>
				</Move>
				<Move>
					<ID>9809</ID>
					<Location>
						<AbsolutePosition>
							<X>87400</X>
							<Y>64000</Y>
							<Z>0</Z>
						</AbsolutePosition>
					</Location>
					<TimeAfter>8</TimeAfter>
				</Move>
			</Action>
		</Item>
		<Item>
			<ID>4</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>Two</Groupings>
				<Threat>Ambiguous</Threat>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				<Reveal>
					<ID>6348</ID>
					<Location>
						<AbsolutePosition>
							<X>52000</X>
							<Y>12400</Y>
							<Z>0</Z>
						</AbsolutePosition>
					</Location>
					<State>FullyFunctional</State>
					<TimeAfter>5</TimeAfter>
				</Reveal>
				<Reveal>
					<ID>7151</ID>
					<Location>
						<AbsolutePosition>
							<X>84800</X>
							<Y>62300</Y>
							<Z>0</Z>
						</AbsolutePosition>
					</Location>
					<State>FullyFunctional</State>
					<TimeAfter>2</TimeAfter>
				</Reveal>
				<Move>
					<ID>6348</ID>
					<Location>
						<AbsolutePosition>
							<X>63600</X>
							<Y>72200</Y>
							<Z>0</Z>
						</AbsolutePosition>
					</Location>
					<TimeAfter>7</TimeAfter>
				</Move>
				<Move>
					<ID>7151</ID>
					<Location>
						<AbsolutePosition>
							<X>25200</X>
							<Y>98400</Y>
							<Z>0</Z>
						</AbsolutePosition>
					</Location>
					<TimeAfter>6</TimeAfter>
				</Move>
			</Action>
		</Item>
		<Item>
			<ID>12</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>Two</Groupings>
				<Threat>Ambiguous</Threat>
				<ThreatType>Non-imminent</ThreatType>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
		<Item>
			<ID>14</ID>
			<Parameters>
				<Crossing>true</Crossing>
				<Groupings>One</Groupings>
				<Threat>Ambiguous</Threat>
				<ThreatType>Non-imminent</ThreatType>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
		<Item>
			<ID>15</ID>
			<Parameters>
				<Crossing>true</Crossing>
				<Groupings>Two</Groupings>
				<Threat>Unambiguous</Threat>
				<ThreatType>Non-imminent</ThreatType>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
		<Item>
			<ID>41</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>One</Groupings>
				<Threat>Unambiguous</Threat>
				<ThreatType>Imminent</ThreatType>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>.75</Difficulty>
			</Parameters>
			<Action>
			
			</Action>
		</Item>
		<Item>
			<ID>60</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>Two</Groupings>
				<Threat>Ambiguous</Threat>
				<ThreatType>Imminent</ThreatType>
				<PlayerResources>Unavailable</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
	</Items>
</SeamateItems>

=== Aptima/DDD/Agents/SEAMATE Item Generator/tags/dec2011tag/SeamateRuntimeEngine/xsd/items.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<SeamateItems xsi:noNamespaceSchemaLocation="items.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Timeline>
		<ScheduledItem>
			<Time>10</Time>
			<ID>4</ID>
			<DM_ID>BAMS DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>70</Time>
			<ID>2</ID>
			<DM_ID>BAMS DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>130</Time>
			<ID>15</ID>
			<DM_ID>BAMS DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>190</Time>
			<ID>60</ID>
			<DM_ID>BAMS DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>250</Time>
			<ID>1</ID>
			<DM_ID>BAMS DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>10</Time>
			<ID>4</ID>
			<DM_ID>Firescout DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>70</Time>
			<ID>2</ID>
			<DM_ID>Firescout DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>130</Time>
			<ID>14</ID>
			<DM_ID>Firescout DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>190</Time>
			<ID>12</ID>
			<DM_ID>Firescout DM</DM_ID>
		</ScheduledItem>
		<ScheduledItem>
			<Time>250</Time>
			<ID>41</ID>
			<DM_ID>Firescout DM</DM_ID>
		</ScheduledItem>
	</Timeline>
	<Items>
		<Item>
			<ID>1</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>One</Groupings>
				<Threat>Unambiguous</Threat>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
		<Item>
			<ID>2</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>One</Groupings>
				<Threat>Ambiguous</Threat>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
		<Item>
			<ID>4</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>Two</Groupings>
				<Threat>Ambiguous</Threat>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
		<Item>
			<ID>12</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>Two</Groupings>
				<Threat>Ambiguous</Threat>
				<ThreatType>Non-imminent</ThreatType>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
		<Item>
			<ID>14</ID>
			<Parameters>
				<Crossing>true</Crossing>
				<Groupings>One</Groupings>
				<Threat>Ambiguous</Threat>
				<ThreatType>Non-imminent</ThreatType>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
		<Item>
			<ID>15</ID>
			<Parameters>
				<Crossing>true</Crossing>
				<Groupings>Two</Groupings>
				<Threat>Unambiguous</Threat>
				<ThreatType>Non-imminent</ThreatType>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
		<Item>
			<ID>41</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>One</Groupings>
				<Threat>Unambiguous</Threat>
				<ThreatType>Imminent</ThreatType>
				<PlayerResources>Available</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>.75</Difficulty>
			</Parameters>
			<Action>
			
			</Action>
		</Item>
		<Item>
			<ID>60</ID>
			<Parameters>
				<Crossing>false</Crossing>
				<Groupings>Two</Groupings>
				<Threat>Ambiguous</Threat>
				<ThreatType>Imminent</ThreatType>
				<PlayerResources>Unavailable</PlayerResources>
				<TeammateResources>Available</TeammateResources>
				<Difficulty>0.20</Difficulty>
			</Parameters>
			<Action>
				
			</Action>
		</Item>
	</Items>
</SeamateItems>
